services:
  haproxy:
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    env_file:
      - .env
    ports:
      - "${HAPROXY_HTTP_PUBLIC_PORT:-80}:${HAPROXY_HTTP_LISTEN_PORT:-80}"

  benchmark:
    build:
      context: ./benchmark
    env_file:
      - .env
    profiles:
      - benchmark
    depends_on:
      - haproxy